import 'package:flutter/material.dart';

import '../statics/data_values.dart';
import '../statics/key_holders.dart';
import '../theme/app_theme.dart';
import '../widgets/container_card.dart';
import '../widgets/frame_title.dart';

class DS3Education extends StatelessWidget {
  const DS3Education({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      key: KeyHolders.educationKey,
      color: AppThemeData.backgroundGrey,
      child: Padding(
        padding: const EdgeInsets.all(40.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            const FrameTitle(
                title: DataValues.educationTitle, description: DataValues.educationDescription),
            const Text('Frontend', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w500)),
            const SizedBox(height: 10),
            SizedBox(
              height: 240,
              child: getGrid(frontend, frontendUrl, frontendNames),
            ),
            const Text('Backend', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w500)),
            const SizedBox(height: 10),
            SizedBox(
              height: 370,
              child: getGrid(backend, backendUrl, backendNames),
            ),
            const Text('DevOps', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w500)),
            const SizedBox(height: 10),
            SizedBox(
              height: 370,
              child: getGrid(devops, null, devopsNames),
            ),
            const Text('Business', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w500)),
            const SizedBox(height: 10),
            SizedBox(
              height: 620,
              child: getGrid(business, businessUrl, businessNames),
            ),
            const Text('Code', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w500)),
            const SizedBox(height: 10),
            SizedBox(
              height: 370,
              child: getGrid(code, codeUrl, codeNames),
            ),
            const Text('Designing', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w500)),
            const SizedBox(height: 10),
            SizedBox(
              height: 370,
              child: getGrid(designing, null, designingNames),
            ),
            const Text('Developer', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w500)),
            const SizedBox(height: 10),
            SizedBox(
              height: 320,
              child: getGrid(developer, null, developerNames),
            ),
          ],
        ),
      ),
    );
  }
}

Widget getGrid(var data, var url, var name) {
  return GridView.builder(
    physics: const NeverScrollableScrollPhysics(),
    gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
      crossAxisCount: 10, // Number of columns
      mainAxisSpacing: 10.0, // Spacing between rows
      crossAxisSpacing: 10.0, // Spacing between columns
    ),
    itemCount: data.length, // Number of items in the grid
    itemBuilder: (BuildContext context, int index) {
      return GridTile(
        child: ContainerCard().type6(
          image: data[index],
          url: url != null ? url[index] : null,
          name: name[index],
        ),
      );
    },
  );
}

var backend = [
  '/backend/dark/appwrite',
  '/backend/dark/auth0',
  '/backend/dark/c',
  '/backend/dark/cpp',
  '/backend/dark/dartfrog',
  '/backend/dark/express-js',
  '/backend/dark/firebase',
  '/backend/dark/firecamp',
  '/backend/dark/graphql',
  '/backend/dark/hoppscotch',
  '/backend/dark/java',
  '/backend/dark/kotlin',
  '/backend/dark/microsoft-dotnet-core',
  '/backend/dark/mongodb',
  '/backend/dark/nhost',
  '/backend/dark/node-js',
  '/backend/dark/postgresql',
  '/backend/dark/postman',
  '/backend/dark/python',
  '/backend/dark/serverpod',
  '/backend/dark/sqlite',
  '/backend/dark/supabase',
  '/backend/dark/swagger',
];
var backendNames = [
  'Appwrite',
  'Auth0',
  'C',
  'Cpp',
  'Dartfrog',
  'Express Js',
  'Firebase',
  'Firecamp',
  'Graphql',
  'Hoppscotch',
  'Java',
  'Kotlin',
  'Dotnet Core',
  'Mongodb',
  'Nhost',
  'Node-js',
  'Postgresql',
  'Postman',
  'Python',
  'Serverpod',
  'Sqlite',
  'Supabase',
  'Swagger',
];

var backendUrl = [
  DataValues.appwriteURL,
  DataValues.auth0URL,
  DataValues.cppURL,
  DataValues.cppURL,
  DataValues.dartFrogURL,
  DataValues.expressJSURL,
  DataValues.firebaseURL,
  DataValues.firecampURL,
  DataValues.graphQLURL,
  DataValues.hoppscotchURL,
  DataValues.javaURL,
  DataValues.kotlinURL,
  DataValues.dotNetURL,
  DataValues.mongoDBURL,
  DataValues.nhostURL,
  DataValues.nodeJSURL,
  DataValues.postgreSQLURL,
  DataValues.postmanURL,
  DataValues.pythonURL,
  DataValues.serverPodURL,
  DataValues.sqliteURL,
  DataValues.supabaseURL,
  DataValues.swaggerURL,
];

var business = [
  '/business/dark/clickup',
  '/business/dark/google-admob',
  '/business/dark/google-ads',
  '/business/dark/google-adsense',
  '/business/dark/google-analytics',
  '/business/dark/google-calendar',
  '/business/dark/google-docs',
  '/business/dark/google-drive',
  '/business/dark/google-forms',
  '/business/dark/google-keep',
  '/business/dark/google-gmail',
  '/business/dark/google-looker-studio',
  '/business/dark/google-maps',
  '/business/dark/google-meet',
  '/business/dark/google-my-business',
  '/business/dark/google-photos',
  '/business/dark/google-play-console',
  '/business/dark/google-search-console',
  '/business/dark/google-sheets',
  '/business/dark/google-slides',
  '/business/dark/google-tag-manager',
  '/business/dark/google-tasks',
  '/business/dark/google-translate',
  '/business/dark/jira',
  '/business/dark/microsoft-365',
  '/business/dark/microsoft-calendar',
  '/business/dark/microsoft-excel',
  '/business/dark/microsoft-forms',
  '/business/dark/microsoft-onedrive',
  '/business/dark/microsoft-onenote',
  '/business/dark/microsoft-outlook',
  '/business/dark/microsoft-powerpoint',
  '/business/dark/microsoft-teams',
  '/business/dark/microsoft-word',
  '/business/dark/microsoft-power-bi',
  '/business/dark/microsoft-outlook',
  '/business/dark/microsoft-todo',
  '/business/dark/notion',
  '/business/dark/sendinblue',
  '/business/dark/slack',
  '/business/dark/trello',
  '/business/dark/zoom',
];
var businessNames = [
  'Clickup',
  'Admob',
  'Ads',
  'Adsense',
  'Analytics',
  'Calendar',
  'Docs',
  'Drive',
  'Forms',
  'Keep',
  'Gmail',
  'Looker-studio',
  'Maps',
  'Meet',
  'My business',
  'Photos',
  'Play console',
  'Search console',
  'Sheets',
  'Slides',
  'Tag-manager',
  'Tasks',
  'Translate',
  'Jira',
  'MS 365',
  'MS Calendar',
  'MS Excel',
  'MS Forms',
  'MS Onedrive',
  'MS Onenote',
  'MS Outlook',
  'MS Powerpoint',
  'MS Teams',
  'MS Word',
  'MS Power-bi',
  'MS Outlook',
  'MS Todo',
  'Notion',
  'Sendinblue',
  'Slack',
  'Trello',
  'Zoom',
];

var businessUrl = [
  DataValues.clickUpURL,
  DataValues.googleAdMobURL,
  DataValues.googleAdsURL,
  DataValues.googleAdsenseURL,
  DataValues.googleAnalyticsURL,
  DataValues.googleCalendarURL,
  DataValues.googleDocsURL,
  DataValues.googleDriveURL,
  DataValues.googleFormsURL,
  DataValues.googleKeepURL,
  DataValues.googleMailURL,
  DataValues.googleLockerStudioURL,
  DataValues.googleMapsURL,
  DataValues.googleMeetURL,
  DataValues.googleMyBusinessURL,
  DataValues.googlePhotosURL,
  DataValues.googlePlayURL,
  DataValues.googleSearchConsoleURL,
  DataValues.googleSheetsURL,
  DataValues.googleSlidesURL,
  DataValues.googleTagManagerURL,
  DataValues.googleTasksURL,
  DataValues.googleTranslateURL,
  DataValues.jiraURL,
  DataValues.ms365URL,
  DataValues.msCalendarURL,
  DataValues.msExcelURL,
  DataValues.msFormsURL,
  DataValues.msOneDriveURL,
  DataValues.msOneNoteURL,
  DataValues.msOutlookURL,
  DataValues.msPowerPointURL,
  DataValues.msTeamsURL,
  DataValues.msWordURL,
  DataValues.msPowerBIURL,
  DataValues.msOutlookURL,
  DataValues.msToDoURL,
  DataValues.notionURL,
  null,
  DataValues.slackURL,
  DataValues.trelloURL,
  DataValues.zoomURL,
  //Dark Mode URLS
];
var code = [
  '/code/dark/android-studio',
  '/code/dark/codepen',
  '/code/dark/codesandbox',
  '/code/dark/codespaces',
  '/code/dark/codewithme',
  '/code/dark/dartpad',
  '/code/dark/fleet',
  '/code/dark/github-copilot',
  '/code/dark/gitpod',
  '/code/dark/intellij-idea',
  '/code/dark/jetbrains-toolbox',
  '/code/dark/jsfiddle',
  '/code/dark/pycharm',
  '/code/dark/replit',
  '/code/dark/stackblitz',
  '/code/dark/sublime-text',
  '/code/dark/visual-studio-code',
  '/code/dark/visual-studio',
  '/code/dark/webstorm',
  '/code/dark/windows-terminal',
  '/code/default/dark', //xcode',
];
var codeNames = [
  'Android Studio',
  'Codepen',
  'Codesandbox',
  'Codespaces',
  'Codewithme',
  'Dartpad',
  'Fleet',
  'Github Copilot',
  'Gitpod',
  'Intellij idea',
  'Jetbrains toolbox',
  'Jsfiddle',
  'Pycharm',
  'Replit',
  'Stackblitz',
  'Sublime Text',
  'VS Code',
  'visual Studio',
  'webstorm',
  'windows Terminal',
  'dark', //xcode',
];

var codeUrl = [
  DataValues.androidStudioURL,
  DataValues.codePenURL,
  DataValues.codesandboxURL,
  null,
  DataValues.codeWithMeURL,
  DataValues.dartPadURL,
  DataValues.fleetURL,
  DataValues.gitHubCoPilotURL,
  DataValues.gitPodURL,
  DataValues.intellijIdeaURL,
  DataValues.jetBrainsToolboxURL,
  DataValues.jSFiddleURL,
  DataValues.pyCharmURL,
  DataValues.replitURL,
  DataValues.stackBlitzURL,
  DataValues.sublimeTextURL,
  DataValues.visualStudioCodeURL,
  DataValues.visualStudioURL,
  DataValues.webStormURL,
  DataValues.windowsTerminalURL,
  null,
];

var designing = [
  '/designing/dark/audacity',
  '/designing/dark/canva',
  '/designing/dark/davinci-resolve',
  '/designing/dark/figma',
  '/designing/dark/flaticon',
  '/designing/dark/freepik',
  '/designing/dark/gimp',
  '/designing/dark/google-fonts',
  '/designing/dark/handbrake',
  '/designing/dark/icons8',
  '/designing/dark/iconscout',
  '/designing/dark/lunacy',
  '/designing/dark/material-design',
  '/designing/dark/obs-studio',
  '/designing/dark/pexels',
  '/designing/dark/photopea',
  '/designing/dark/pixabay',
  '/designing/dark/playbook',
  '/designing/dark/powertoys',
  '/designing/dark/undraw',
  '/designing/dark/unsplash',
  '/designing/dark/wepik',
];

var designingNames = [
  'Audacity',
  'Canva',
  'Davinci Resolve',
  'Figma',
  'Flaticon',
  'Freepik',
  'Gimp',
  'Google Fonts',
  'Handbrake',
  'Icons8',
  'Iconscout',
  'Lunacy',
  'Material Design',
  'Obs Studio',
  'Pexels',
  'Photopea',
  'Pixabay',
  'Playbook',
  'Powertoys',
  'Undraw',
  'Unsplash',
  'Wepik',
];

var developer = [
  '/developer/dark/behance',
  '/developer/dark/codechef',
  '/developer/dark/codeproject',
  '/developer/dark/codersrank',
  '/developer/dark/dribbble',
  '/developer/dark/freecodecamp',
  '/developer/dark/glitch',
  '/developer/dark/google',
  '/developer/dark/googledevelopers',
  '/developer/dark/gravatar',
  '/developer/dark/hackerrank',
  '/developer/dark/hackerearth',
  '/developer/dark/kaggle',
  '/developer/dark/keybase',
  '/developer/dark/leetcode',
  '/developer/dark/microsoft',
  '/developer/dark/mlsa',
  '/developer/dark/producthunt',
  '/developer/dark/stackoverflow',
  '/developer/dark/topcoder',
];

var developerNames = [
  'Behance',
  'Codechef',
  'Codeproject',
  'Codersrank',
  'Dribbble',
  'Freecodecamp',
  'Glitch',
  'Google',
  'Googledevelopers',
  'Gravatar',
  'Hackerrank',
  'Hackerearth',
  'Kaggle',
  'Keybase',
  'Leetcode',
  'Microsoft',
  'Mlsa',
  'Producthunt',
  'Stackoverflow',
  'Topcoder',
];

var devops = [
  '/devops/dark/appstore',
  '/devops/dark/aws',
  '/devops/dark/bitbucket',
  '/devops/dark/bitrise',
  '/devops/dark/circleci',
  '/devops/dark/cloudflare',
  '/devops/dark/codemagic',
  '/devops/dark/digitalocean',
  '/devops/dark/docker',
  '/devops/dark/git',
  '/devops/dark/github',
  '/devops/dark/gitkraken',
  '/devops/dark/gitlab',
  '/devops/dark/google-cloud-platform',
  '/devops/dark/google-play',
  '/devops/dark/microsoft-azure',
  '/devops/dark/microsoft-store',
  '/devops/dark/netlify',
  '/devops/dark/sentry',
  '/devops/dark/vercel',
];
var devopsNames = [
  'App Store',
  'AWS',
  'Bitbucket',
  'Bitrise',
  'Circleci',
  'Cloudflare',
  'Codemagic',
  'Digitalocean',
  'Docker',
  'Git',
  'Github',
  'Gitkraken',
  'Gitlab',
  'GCP',
  'Google Play',
  'Azure',
  'Microsoft Store',
  'Netlify',
  'Sentry',
  'Vercel',
];

var devopsUrl = [
  DataValues.appStoreURL,
  DataValues.awsURL,
  DataValues.bitBucketURL,
  DataValues.bitriseURL,
  DataValues.circleCIURL,
  DataValues.cloudflareURL,
  DataValues.codemagicURL,
  DataValues.digitalOceanURL,
  DataValues.dockerURL,
  DataValues.gitURL,
  DataValues.githubURL,
  DataValues.gitKrakenURL,
  DataValues.gitlabURL,
  DataValues.googleCloudURL,
  DataValues.googlePlayURL,
  DataValues.azureURL,
  DataValues.microsoftStoreURL,
  DataValues.netlifyURL,
  DataValues.sentryURL,
  DataValues.vercelURL,
];
var frontend = [
  '/frontend/dark/android',
  '/frontend/dark/bootstrap',
  '/frontend/dark/c-sharp',
  '/frontend/dark/css',
  '/frontend/dark/dart',
  '/frontend/dark/flutter',
  '/frontend/dark/flutterflow',
  '/frontend/dark/google-sites',
  '/frontend/dark/html',
  '/frontend/dark/javascript',
  '/frontend/dark/microsoft-dotnet',
  '/frontend/dark/next-js',
  '/frontend/dark/react',
  '/frontend/dark/wix',
  '/frontend/dark/wordpress',
  '/frontend/dark/xamarin',
];
var frontendNames = [
  'Android',
  'Bootstrap',
  'C Sharp',
  'Css',
  'Dart',
  'Flutter',
  'Flutter Flow',
  'Google Sites',
  'HTML',
  'Javascript',
  'Dotnet',
  'Next Js',
  'React',
  'Wix',
  'Wordpress',
  'Xamarin',
];

var frontendUrl = [
  DataValues.androidURL,
  DataValues.bootstrapURL,
  DataValues.cSharpURL,
  DataValues.cssURL,
  DataValues.dartURL,
  DataValues.flutterURL,
  DataValues.flutterFlowURL,
  DataValues.googleSitesURL,
  DataValues.htmlURL,
  DataValues.javascriptURL,
  DataValues.dotNetURL,
  DataValues.nextJSURL,
  DataValues.reactURL,
  DataValues.wixURL,
  DataValues.wordpressURL,
  DataValues.xamarinURL,
  //Dark Mode URLS
];
